### ISSUE TITLE
invalid_grant: Reused authorization code: OsF4KO

### ISSUE THREAD

**Issue by tpolecat** [gemini-hlsw/lucuma-sso#16]
This should never happen … figure out how it did!

```
2020-08-28T21:24:16.905005+00:00 app[web.1]: [ERROR] lucuma-sso - Error servicing request: GET /auth/stage2 from <unknown>
2020-08-28T21:24:16.905046+00:00 app[web.1]: orcid.lucuma.sso.service.orcid.OrcidException: invalid_grant: Reused authorization code: OsF4KO
2020-08-28T21:24:16.905068+00:00 app[web.1]: at orcid.lucuma.sso.service.orcid.OrcidException$.$anonfun$DecoderOrcidException$3(OrcidException.scala:22)
2020-08-28T21:24:16.905086+00:00 app[web.1]: at scala.util.Either.map(Either.scala:382)
2020-08-28T21:24:16.905104+00:00 app[web.1]: at orcid.lucuma.sso.service.orcid.OrcidException$.$anonfun$DecoderOrcidException$2(OrcidException.scala:21)
2020-08-28T21:24:16.905136+00:00 app[web.1]: at scala.util.Either.flatMap(Either.scala:352)
2020-08-28T21:24:16.905157+00:00 app[web.1]: at orcid.lucuma.sso.service.orcid.OrcidException$.orcid$lucuma$sso$service$orcid$OrcidException$$$anonfun$DecoderOrcidException$1(OrcidException.scala:20)
2020-08-28T21:24:16.905161+00:00 app[web.1]: at orcid.lucuma.sso.service.orcid.OrcidException$$anonfun$1.apply(OrcidException.scala:18)
2020-08-28T21:24:16.905180+00:00 app[web.1]: at io.circe.Decoder.decodeJson(Decoder.scala:86)
2020-08-28T21:24:16.905197+00:00 app[web.1]: at io.circe.Decoder.decodeJson$(Decoder.scala:86)
2020-08-28T21:24:16.905214+00:00 app[web.1]: at orcid.lucuma.sso.service.orcid.OrcidException$$anonfun$1.decodeJson(OrcidException.scala:18)
2020-08-28T21:24:16.905231+00:00 app[web.1]: at org.http4s.circe.CirceInstances.$anonfun$jsonOfWithMedia$1(CirceInstances.scala:74)
2020-08-28T21:24:16.905248+00:00 app[web.1]: at cats.data.EitherT.$anonfun$flatMap$1(EitherT.scala:355)
2020-08-28T21:24:16.905272+00:00 app[web.1]: at scala.Function1.$anonfun$andThen$1(Function1.scala:85)
2020-08-28T21:24:16.905289+00:00 app[web.1]: at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:145)
2020-08-28T21:24:16.905306+00:00 app[web.1]: at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:366)
2020-08-28T21:24:16.905323+00:00 app[web.1]: at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:387)
2020-08-28T21:24:16.905340+00:00 app[web.1]: at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:330)
2020-08-28T21:24:16.905357+00:00 app[web.1]: at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:141)
2020-08-28T21:24:16.905373+00:00 app[web.1]: at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:366)
2020-08-28T21:24:16.905391+00:00 app[web.1]: at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:387)
2020-08-28T21:24:16.905410+00:00 app[web.1]: at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:330)
```

**Comment by tpolecat** [comment]
This can happen if Ember client barfs in stage 2 and then you hit refresh, which cause it to try again with an invalid token. We need to either figure out why Ember is unstable or switch to Blaze.
