### ISSUE TITLE
The token will only be valid after

### ISSUE THREAD

**Issue by swalker2m** [gemini-hlsw/lucuma-sso#334]
I first ran into this issue when updating `cats-time` to `0.5.0`.  Now I'm back on `0.4.0` but I still get

```
service pdi.jwt.exceptions.JwtNotBeforeException: The token will only be valid after 2021-11-23T16:24:29Z
service 	at pdi.jwt.JwtTime$.validateNowIsBetween(JwtTime.scala:57)
service 	at pdi.jwt.JwtTime$.validateNowIsBetweenSeconds(JwtTime.scala:73)
service 	at pdi.jwt.JwtCore.validateTiming(Jwt.scala:561)
service 	at pdi.jwt.JwtCore.validateTiming$(Jwt.scala:554)
service 	at pdi.jwt.Jwt$.validateTiming(JwtPureScala.scala:19)
service 	at pdi.jwt.JwtCore.validate(Jwt.scala:614)
service 	at pdi.jwt.JwtCore.validate$(Jwt.scala:594)
service 	at pdi.jwt.Jwt$.validate(JwtPureScala.scala:19)
service 	at pdi.jwt.JwtCore.validate(Jwt.scala:643)
service 	at pdi.jwt.JwtCore.validate$(Jwt.scala:642)
service 	at pdi.jwt.Jwt$.validate(JwtPureScala.scala:19)
service 	at pdi.jwt.JwtCore.$anonfun$decodeAll$5(Jwt.scala:453)
service 	at scala.util.Try$.apply(Try.scala:210)
service 	at pdi.jwt.JwtCore.decodeAll(Jwt.scala:450)
service 	at pdi.jwt.JwtCore.decodeAll$(Jwt.scala:450)
service 	at pdi.jwt.Jwt$.decodeAll(JwtPureScala.scala:19)
service 	at pdi.jwt.JwtCore.decode(Jwt.scala:538)
service 	at pdi.jwt.JwtCore.decode$(Jwt.scala:537)
service 	at pdi.jwt.Jwt$.decode(JwtPureScala.scala:19)
service 	at pdi.jwt.JwtCore.decode(Jwt.scala:549)
service 	at pdi.jwt.JwtCore.decode$(Jwt.scala:549)
service 	at pdi.jwt.Jwt$.decode(JwtPureScala.scala:19)
service 	at pdi.jwt.JwtCore.decode(Jwt.scala:551)
service 	at pdi.jwt.JwtCore.decode$(Jwt.scala:551)
service 	at pdi.jwt.Jwt$.decode(JwtPureScala.scala:19)
service 	at lucuma.sso.client.util.JwtDecoder$$anon$1.attemptDecode(JwtDecoder.scala:54)
service 	at lucuma.sso.client.util.JwtDecoder$$anon$1.decode(JwtDecoder.scala:64)
service 	at lucuma.sso.client.SsoJwtReader$$anon$1.decodeClaim(SsoJwtReader.scala:78)
service 	at lucuma.sso.client.SsoClient$.$anonfun$initial$6(SsoClient.scala:117)
service 	at flatMap @ lucuma.sso.client.util.JwtDecoder$$anon$1.decode(JwtDecoder.scala:64)
service 	at map @ lucuma.sso.client.SsoJwtReader$$anon$1.decodeClaim(SsoJwtReader.scala:78)
service 	at flatMap @ lucuma.sso.client.SsoClient$.$anonfun$initial$6(SsoClient.scala:117)
service 	at delay @ org.http4s.blaze.client.PoolManager.addToIdleQueue(PoolManager.scala:141)
service 	at delay @ org.http4s.blaze.client.PoolManager.$anonfun$releaseRecyclable$3(PoolManager.scala:234)
service 	at delay @ org.http4s.blaze.client.PoolManager.releaseRecyclable(PoolManager.scala:223)
service 	at flatMap @ org.http4s.blaze.client.PoolManager.releaseRecyclable(PoolManager.scala:223)
```

Is seems like there is some inconsistency between client and server.

**Comment by tpolecat** [comment]
I'm seeing this in the ODB now. I think this happens because of clock skew. If the local system and SSO disagree on what time it is then it's possible for a JWT to appear have been issued in the [near] future. I should be able to fix this by issuing tokens a few seconds in the past.

**Comment by swalker2m** [comment]
I could be misremembering but it seemed like the difference was hours, not seconds.

**Comment by tpolecat** [comment]
Interesting, I wonder if the heroku clocks are sometimes wildly off. That would be strange.
